### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by sambeck87** [sambeck87/react_redux_project#25]
https://github.com/sambeck87/react_redux_project/projects/1
We are 3 developers (@belaymit and  @sambeck87 @Vgonma )

**Comment by pinkmoon25** [comment]
Hi @sambeck87 and @belaymit , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/XreQmk7ETCak0/giphy.gif"/>

## Highlights
Kanban setup :heavy_check_mark: 

## Optional suggestions

- [ ] **[Optional] Please close all the issues for Team3 tasks as you guys are 2 Devs team.**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
